version: '3.10'

services:

  web:

    build:
      context: ./
    tty: true
    ports:
      - "8000:8000"
    networks:
      - ssh_net

  ssh:

    build: ./ssh
    depends_on:
      - web
    tty: true
    volumes:
      - type: bind
        source: ~/.ssh
        target : /root/.ssh
    networks:
      - ssh_net

networks:
  ssh_net:
